# flake8: noqa

from pytest_celery.components.backend.memcached import MemcachedTestBackend
from pytest_celery.components.backend.memcached import celery_memcached_backend
from pytest_celery.components.backend.memcached import default_memcached_backend
from pytest_celery.components.backend.memcached import default_memcached_backend_celeryconfig
from pytest_celery.components.backend.memcached import default_memcached_backend_cls
from pytest_celery.components.backend.memcached import default_memcached_backend_env
from pytest_celery.components.backend.memcached import default_memcached_backend_image
from pytest_celery.components.backend.memcached import default_memcached_backend_ports
from pytest_celery.components.backend.redis import RedisTestBackend
from pytest_celery.components.backend.redis import celery_redis_backend
from pytest_celery.components.backend.redis import default_redis_backend
from pytest_celery.components.backend.redis import default_redis_backend_celeryconfig
from pytest_celery.components.backend.redis import default_redis_backend_cls
from pytest_celery.components.backend.redis import default_redis_backend_env
from pytest_celery.components.backend.redis import default_redis_backend_image
from pytest_celery.components.backend.redis import default_redis_backend_ports
