version: "3"

services:
  worker:
    build: .
    command: celery -A app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - rabbitmq
    networks:
      - my_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    networks:
      - my_network

networks:
  my_network:
